### ISSUE TITLE
Encore

### ISSUE THREAD

**Issue by dkarlovi** [sigwinhq/infra#8]
```yaml
encore: | node_modules
	BASE_URL=http://localhost/ node_modules/.bin/encore production
node_modules:
	npm install
```
